-- Script para Supabase: Caso 2 - Registro de mascotas para veterinaria
-- Ejecutar completo en Supabase > SQL Editor > New query.

create table if not exists public.especies (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.razas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  especie_id bigint references public.especies(id) on delete set null,
  constraint razas_nombre_unique unique (nombre)
);

create table if not exists public.tipos_atencion (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.condiciones_medicas (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.mascotas (
  id bigint generated by default as identity primary key,
  nombre_mascota text not null,
  edad_mascota integer not null check (edad_mascota >= 0),
  peso numeric(6,2) not null check (peso >= 0),
  nombre_dueno text not null,
  apellido_dueno text not null,
  dni_dueno text not null check (dni_dueno ~ '^[0-9]{8}$'),
  celular text not null,
  correo text not null,
  especie_id bigint not null references public.especies(id),
  raza_id bigint not null references public.razas(id),
  tipo_atencion_id bigint not null references public.tipos_atencion(id),
  condicion_medica_id bigint not null references public.condiciones_medicas(id),
  observaciones text,
  created_at timestamptz not null default now()
);

insert into public.especies (nombre) values
  ('Perro'),
  ('Gato'),
  ('Conejo'),
  ('Ave'),
  ('Otro')
on conflict (nombre) do nothing;

insert into public.razas (nombre) values
  ('Mestizo'),
  ('Labrador'),
  ('Bulldog'),
  ('Schnauzer'),
  ('Persa'),
  ('Siames'),
  ('Otro')
on conflict (nombre) do nothing;

insert into public.tipos_atencion (nombre) values
  ('Consulta general'),
  ('Vacunacion'),
  ('Desparasitacion'),
  ('Emergencia'),
  ('Control'),
  ('Cirugia')
on conflict (nombre) do nothing;

insert into public.condiciones_medicas (nombre) values
  ('Ninguna'),
  ('Alergia'),
  ('Infeccion'),
  ('Fractura'),
  ('Problema digestivo'),
  ('Problema respiratorio'),
  ('Otra')
on conflict (nombre) do nothing;

alter table public.especies enable row level security;
alter table public.razas enable row level security;
alter table public.tipos_atencion enable row level security;
alter table public.condiciones_medicas enable row level security;
alter table public.mascotas enable row level security;

drop policy if exists "Lectura publica especies" on public.especies;
drop policy if exists "Lectura publica razas" on public.razas;
drop policy if exists "Lectura publica tipos_atencion" on public.tipos_atencion;
drop policy if exists "Lectura publica condiciones_medicas" on public.condiciones_medicas;
drop policy if exists "Lectura publica mascotas" on public.mascotas;
drop policy if exists "Insert publico mascotas" on public.mascotas;

create policy "Lectura publica especies"
on public.especies for select
to anon, authenticated
using (true);

create policy "Lectura publica razas"
on public.razas for select
to anon, authenticated
using (true);

create policy "Lectura publica tipos_atencion"
on public.tipos_atencion for select
to anon, authenticated
using (true);

create policy "Lectura publica condiciones_medicas"
on public.condiciones_medicas for select
to anon, authenticated
using (true);

create policy "Lectura publica mascotas"
on public.mascotas for select
to anon, authenticated
using (true);

create policy "Insert publico mascotas"
on public.mascotas for insert
to anon, authenticated
with check (true);

-- Registro obligatorio de identificacion:
-- Despues de crear las tablas, registra desde la web la primera mascota usando
-- tus propios datos como dueno. Ese primer registro debe aparecer en la captura.
